language: objective-c
cache: bundler
xcode_project: Applozic-iOS-SDK/Applozic-framework/Applozic.xcodeproj
script:
  - xcodebuild -project Applozic-iOS-SDK/Applozic-framework/Applozic.xcodeproj -scheme Applozic -sdk iphonesimulator

notifications:
  email:
    recipients:
      - global@mobitexter.net
      - devashish@applozic.com
      - adarsh@applozic.com
      - ranjeet@applozic.com

