language: objective-c
osx_image: xcode7.3
xcode_project: Applozic.xcodeproj
xcode_scheme: Applozic

#before_install:
#   -chmod +x travis/before_script.sh
#before_script: travis/before_script.sh
#script: travis/script.sh

#script: xcodebuild -workspace ~/sample-with-framework/Applozic.xcworkspace -scheme Applozic -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO

#notifications:
 # email:
  #  recipients:
    

