language: objective-c
osx_image: xcode7.3
xcode_project: applozicdemo.xcodeproj
xcode_scheme: applozicdemo

#before_install:
#   -chmod +x travis/before_script.sh
#before_script: travis/before_script.sh
#script: travis/script.sh

script: xcodebuild -project ~/build/Applozic/Applozic-iOS-SDK/sample-with-framework/applozicdemo.xcodeproj -scheme applozicdemo 
#script: pwd 
#notifications:
 # email:
  #  recipients:
    

