language: objective-c
cache: bundler
xcode_project: Applozic-iOS-SDK/Applozic-framework/Applozic.xcodeproj

notifications:
  email:
    recipients:
      - global@mobitexter.net
      - devashish@applozic.com
      - adarsh@applozic.com
      - ranjeet@applozic.com

