language: objective-c
osx_image: xcode7

#before_install:
#   -chmod +x travis/before_script.sh
#before_script: travis/before_script.sh
#script: travis/script.sh

script:
      - make build

notifications:
  email:
    recipients:
      - ranjeet@applozic.com

